version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: danat_db
      POSTGRES_USER: danat_user
      POSTGRES_PASSWORD: danat_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: